Exemples d'extraction de données à partir de l'API OpenSky

1) Extraction des informations sur les avions (state vestors)

- Les informations qui concernent tous les avions à l'instant actuel (les state vectors):

In [2]:
import pandas as pd
import requests
import json

user_name='rim-DE'
password='bde_airlines'

In [14]:
OpenSky_url = 'https://'+user_name+':'+password+'@opensky-network.org/api/states/all'
OpenSky_data = requests.get(OpenSky_url).json()

try:
    columns = ['icao24','callsign','origin_country','time_position','last_contact','long','lat','baro_altitude','on_ground (T/F)','velocity','true_track','vertical_rate','sensors',
    'geo_altitude','squawk','spi','position_source','category']
    flight_df=pd.DataFrame(OpenSky_data['states'],columns=columns)
    flight_df=flight_df.fillna('No Data')
except ValueError:
    columns = ['icao24','callsign','origin_country','time_position','last_contact','long','lat','baro_altitude','on_ground (T/F)','velocity','true_track','vertical_rate','sensors',
    'geo_altitude','squawk','spi','position_source']
    flight_df=pd.DataFrame(OpenSky_data['states'],columns=columns)
    flight_df=flight_df.fillna('No Data')

flight_df.head()

,icao24,callsign,origin_country,time_position,last_contact,long,lat,baro_altitude,on_ground (T/F),velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source
0,4b1814,SWR206R,Switzerland,1667150423.0,1667150423,9.184,47.7548,6301.74,False,233.7,24.31,10.73,No Data,6598.92,3005,False,0
1,4b1815,SWR262C,Switzerland,1667150423.0,1667150423,6.9406,46.4238,9144.0,False,236.07,52.08,0.0,No Data,9486.9,1000,False,0
2,4b1816,SWR1BA,Switzerland,1667150422.0,1667150422,20.1364,40.4484,10972.8,False,231.11,322.42,0.0,No Data,11300.46,No Data,False,0
3,c07d0b,CGVJE,Canada,1667150151.0,1667150151,-73.4108,45.5215,No Data,True,6.43,135.00,No Data,No Data,No Data,No Data,False,0
4,e49408,PTGCR,Brazil,No Data,1667150423,No Data,No Data,No Data,False,208.46,213.73,-0.33,No Data,No Data,No Data,False,0

- Les informations d'un avion donné à un instant donnée:

In [9]:
OpenSky_url = 'https://'+user_name+':'+password+'@opensky-network.org/api/states/all?time=1458564121&icao24=3c6444'
OpenSky_data = requests.get(OpenSky_url).json()

print (OpenSky_data)

try:
    columns = ['icao24','callsign','origin_country','time_position','last_contact','long','lat','baro_altitude','on_ground (T/F)','velocity','true_track','vertical_rate','sensors',
    'geo_altitude','squawk','spi','position_source','category']
    flight_df=pd.DataFrame(OpenSky_data['states'],columns=columns)
    flight_df=flight_df.fillna('No Data')
except ValueError:
    columns = ['icao24','callsign','origin_country','time_position','last_contact','long','lat','baro_altitude','on_ground (T/F)','velocity','true_track','vertical_rate','sensors',
    'geo_altitude','squawk','spi','position_source']
    flight_df=pd.DataFrame(OpenSky_data['states'],columns=columns)
    flight_df=flight_df.fillna('No Data')

flight_df.head()

{'time': 1458564121, 'states': [['3c6444', 'DLH9LF  ', 'Germany', 1458564120, 1458564120, 6.1546, 50.1964, 9639.3, False, 232.88, 98.26, 4.55, None, 9547.86, '1000', False, 0]]}

,icao24,callsign,origin_country,time_position,last_contact,long,lat,baro_altitude,on_ground (T/F),velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source
0,3c6444,DLH9LF,Germany,1458564120,1458564120,6.1546,50.1964,9639.3,False,232.88,98.26,4.55,No Data,9547.86,1000,False,0

2) Extraction des informations sur les vols

    Remarque: Les vols sont mis à jour par un traitement batch la nuit, c'est-à-dire que seuls les vols de la veille ou d'avant sont disponibles.

- Informations des vols pour un interval de temps donné:

In [17]:
OpenSky_url = 'https://'+user_name+':'+password+'@opensky-network.org/api/flights/all?begin=1517227200&end=1517230800'
OpenSky_data = requests.get(OpenSky_url).json()


columns = ['icao24','firstSeen','estDepartureAirport','lastSeen','estArrivalAirport','callsign','estDepartureAirportHorizDistance',
'estDepartureAirportVertDistance','estArrivalAirportHorizDistance','estArrivalAirportVertDistance','departureAirportCandidatesCount',
'arrivalAirportCandidatesCount']
flight_df=pd.DataFrame(OpenSky_data,columns=columns)
flight_df=flight_df.fillna('No Data')


flight_df.head()

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,c078fd,1517227317,CYYZ,1517230676,CYUL,SWG9426,525.0,104.0,3244.0,81.0,1,1
1,8686b2,1517229296,No Data,1517230536,RJTK,JAL920,No Data,No Data,15167.0,1421.0,0,1
2,e491f0,1517229076,No Data,1517230486,SBMT,ONE6105,No Data,No Data,6467.0,566.0,0,2
3,3e3a2c,1517227395,EDFZ,1517228367,EDRI,DINFO,2059.0,175.0,12600.0,1638.0,0,2
4,4ca88c,1517227634,No Data,1517230768,No Data,RYR55HX,No Data,No Data,No Data,No Data,0,0

Les informations sur les vols d'un airoport donné (e.g Frankfurt International Airport (EDDF)) à un interval de temps donné (from 12pm to 1pm on Jan 29 2018).

In [18]:
OpenSky_url = 'https://'+user_name+':'+password+'@opensky-network.org/api/flights/arrival?airport=EDDF&begin=1517227200&end=1517230800'
OpenSky_data = requests.get(OpenSky_url).json()


columns = ['icao24','firstSeen','estDepartureAirport','lastSeen','estArrivalAirport','callsign','estDepartureAirportHorizDistance',
'estDepartureAirportVertDistance','estArrivalAirportHorizDistance','estArrivalAirportVertDistance','departureAirportCandidatesCount',
'arrivalAirportCandidatesCount']
flight_df=pd.DataFrame(OpenSky_data,columns=columns)
flight_df=flight_df.fillna('No Data')


flight_df.head()

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,0101be,1517220729,No Data,1517230737,EDDF,MSR785,No Data,No Data,1593,95,0,2
1,3c6675,1517227831,EDDT,1517230709,EDDF,DLH187,191.0,54.0,3000,103,1,3
2,3c6663,1517226907,No Data,1517230498,EDDF,DLH8JT,No Data,No Data,3307,126,0,3
3,3c64c3,1517196397,No Data,1517230408,EDDF,DLH543,No Data,No Data,4478,126,0,3
4,501d7d,1517222295,No Data,1517230331,EDDF,ADR114,No Data,No Data,357,95,0,2